[pytest]
testpaths = testcase
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --alluredir=report/allure-results --clean-alluredir --html=report/report.html --self-contained-html
